/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gitmetadatapoc;
import datadog.trace.api.Trace;

public class App {
    @Trace(operationName = "getGreeting", resourceName = "GradleApp")
    public String getGreeting() {
        throw new ArithmeticException( "Some exception" );
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
